class SavedTokenError(Exception):
    pass


class AuthError(Exception):
    pass
